name: name: Production Deployment

on:
  release:
  types: # This configuration does not affect the page_build event above
    - published

jobs:
  test-release-trigger:
    name: test-release-trigger
    runs-on: ubuntu-latest
    steps:
      - name: print test
        run: |
          echo "Test Release"
