name: name: Production Deployment

on:
  push:
    branches:
      - refs/tags/*

jobs:
  test-release-trigger:
    name: test-release-trigger
    runs-on: ubuntu-latest
    steps:
      - name: print test
        run: |
          echo "Test Release"
