name: Production Deployment

on:
  release:
    types: [published]


jobs:
  test-release-trigger:
    name: test-release-trigger
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: print test

        run: |
          echo "Test Release"
